app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin.login.check:
    path: /admin/login_check

admin.logout:
    path: /admin/logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /business