app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin.login.check:
    path: /admin/login_check

admin.logout:
    path: /admin/logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /business

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /business/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /business/profile